import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-white">
        
        <Header />
        
        {/* flex-grow stretches this container vertically to push footer to the bottom */}
        {/* max-w-[1050px] locks your content to your target horizontal layout grid */}
        <main className="w-full max-w-[1050px] mx-auto px-4 sm:px-6 lg:px-8 flex-grow py-8">
          {children}
        </main>
        
        <Footer />
        
      </body>
    </html>
  );
}
